// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPXpcYUwNG5B2wDlg2_p1LOrdRq9W05LY',
    appId: '1:650577934506:web:24f83e7a05accaeb0bf8d3',
    messagingSenderId: '650577934506',
    projectId: 'intern-47419',
    authDomain: 'intern-47419.firebaseapp.com',
    storageBucket: 'intern-47419.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-yPY-Nzb3K7AEoaVE3SbG74Lq_7QlFv4',
    appId: '1:650577934506:android:6914da25074e6cfb0bf8d3',
    messagingSenderId: '650577934506',
    projectId: 'intern-47419',
    storageBucket: 'intern-47419.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT73MA27akQy9rWkKDB1nJ36KeObHZDlc',
    appId: '1:650577934506:ios:f760c9e0226e38e90bf8d3',
    messagingSenderId: '650577934506',
    projectId: 'intern-47419',
    storageBucket: 'intern-47419.appspot.com',
    iosBundleId: 'com.example.internship',
  );
}
